[versions]
coroutines = "1.4.2"
ktor = "1.4.3"
kotest = "4.3.2"
logger = "0.12.0"
okHttp = "4.9.0"
retrofit = "2.9.0"
retrofitConverter = "0.8.0"
serialization = "1.0.1"
turbine = "0.4.0-SNAPSHOT"

[dependencies]
common-main-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
common-main-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
common-main-logger-serialization = { group = "com.javiersc.logger", name = "logger-serialization", version.ref = "logger" }
common-main-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
common-main-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

common-test-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
common-test-kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
common-test-kotlin-test-annotations = { group = "org.jetbrains.kotlin", name = "kotlin-test-annotations-common" }
common-test-kotlin-test-common = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
common-test-kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }
common-test-ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
common-test-ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
common-test-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

jvm-main-ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
jvm-main-okHttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
jvm-main-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

jvm-test-okHttp3-mockWebServer = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okHttp" }
jvm-test-retrofit2-converter-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitConverter" }
